### ISSUE TITLE
Easy way to run idea-ultimate stable

### ISSUE THREAD

**Issue by oliverbestmann** [BananchickPasha/jbr-wayland-nix#3]
I am using this flake now for around a month or more.
Today i got the message `IntelliJ IDEA EAP Build Expired` when starting idea-ultimate (even with the most recent commit of this flake). Especially now with `2024.1` being already released, is there an easy way to always run the latest stable version instead of the EAP/Beta versions using this flake?

**Comment by BananchickPasha** [comment]
I haven't moved all editors to stable branch as I didn't know how many of them already have 2024.1 version, but turns out all of them have it. I've updated `versions.json` so just update your flakes to try this out

Also you can provide your custom overlay with any version you want, as it's described in `readme.md`

**Comment by oliverbestmann** [comment]
Thanks. I would have loved something like `jetbrains.eap.idea-ultimate` or `jetbrains.stable.idea-ultimate`... but i can live with an overlay. 

But now the plugins are outdated ;) Can i also specify the plugins via an overlay?

**Comment by BananchickPasha** [comment]
>But now the plugins are outdated

I've run update script again, now they should be up to date. 
> Can i also specify the plugins via an overlay?

Definitelly not from my overlay, but as I've just copied most of the code from nixpkgs, maybe there are existing way to specify their versions. I dont use plugins so I don't know

**Comment by oliverbestmann** [comment]
Thanks!
